# coding: utf-8

"""
    MBTA

    MBTA service API. https://www.mbta.com

    OpenAPI spec version: 3.0
    Contact: developer@mbta.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.route_api import RouteApi


class TestRouteApi(unittest.TestCase):
    """ RouteApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.route_api.RouteApi()

    def tearDown(self):
        pass

    def test_api_route_controller_index(self):
        """
        Test case for api_route_controller_index

        
        """
        pass

    def test_api_route_controller_show(self):
        """
        Test case for api_route_controller_show

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
